[package]
name = "flamenco687/maid"
description = "Roblox library to manage connections and tasks"

version = "1.4.0"
license = "Apache 2.0"

authors = ["flamenco687", "finobinos"]
realm = "shared"

registry = "https://github.com/UpliftGames/wally-index"

exclude = ["LICENSE", "README.md"]
